xcenter.org.id=1
xcenter.rtl_location.id=0
xcenter.wkstn.id=0

dtv.CustomerId=LEV
dtv.CustomerId.salt=LEVICORP

dtv.location.CurrencyId=USD

xstore.config.path.base.features=:cust:cust/loyalty:cust/loyalty/award:purge:order:locate:relate
xstore.config.path.global.extensions=:dataloader:xcenter:xcenter/event_log:xcenter/xbr

# JDBC driver/connection factory
dtv.datasource.connectionfactory=oracle.jdbc.pool.OracleDataSource

dtv.local.db.url=jdbc:oracle:thin:@localhost:1521:xcenter
# PDB dtv.local.db.url=jdbc:oracle:thin:@localhost:1521/xcenter
# Wallet dtv.local.db.url=jdbc:oracle:thin:@atpconnection_tp?TNS_ADMIN=/path/to/wallet
dtv.local.db.user=Pj4+MAAAAABEJKQVOAJI+5sGlAQ30XIQ
dtv.local.db.password=Pj4+MAAAAABEJKQVOAJI+5sGlAQ30XIQ
dtv.local.db.disableencryption=false

dtv.xadmin.db.url=jdbc:oracle:thin:@localhost:1521:xcenter
# PDB dtv.xadmin.db.url=jdbc:oracle:thin:@localhost:1521/xcenter
# Wallet dtv.xadmin.db.url=jdbc:oracle:thin:@atpconnection_tp?TNS_ADMIN=/path/to/wallet
dtv.xadmin.db.user=Pj4+MAAAAABEJKQVOAJI+5sGlAQ30XIQ
dtv.xadmin.db.password=Pj4+MAAAAABEJKQVOAJI+5sGlAQ30XIQ
dtv.xadmin.db.disableencryption=false

dtv.xcrepl.db.url=jdbc:oracle:thin:@localhost:1521:xcenter
# PDB dtv.xcrepl.db.url=jdbc:oracle:thin:@localhost:1521/xcenter
# Wallet dtv.xcrepl.db.url=jdbc:oracle:thin:@atpconnection_tp?TNS_ADMIN=/path/to/wallet
dtv.xcrepl.db.user=Pj4+MAAAAABEJKQVOAJI+5sGlAQ30XIQ
dtv.xcrepl.db.password=Pj4+MAAAAABEJKQVOAJI+5sGlAQ30XIQ
dtv.xcrepl.db.disableencryption=false

dtv.xadmin.baseURL=https://localhost:8443/xadmin/

dtv.xadmin.smtp.host=localhost
dtv.xadmin.smtp.port=25
dtv.xadmin.smtp.auth=false
dtv.xadmin.smtp.user=
dtv.xadmin.smtp.password=
dtv.xadmin.smtp.sender=noreply@xadmin.com
dtv.xadmin.smtp.starttls=true

# Location to transfer staged deployments. Can be http(s):// for Apache web server or file:// for FTP server. 
dtv.deployment.StagingHostBaseURL=https://staginghost/
dtv.deployment.StagingHostUsername=Pj4+MAAAAADvHIxh8KlKpMb58080fuVH
dtv.deployment.StagingHostPassword=Pj4+MAAAAACxzvu3yc0wTglnR9h+w5f6

# Files that are uploaded to Xcenter from Xstore via Xenviroment are saved here.
# This dir must be mapable to the Xadmin runtime for the FilePurgerJob to delete files here.
dtv.pospolls.workingDir=file:/pospoll

# FileResource containers
xst.fileresource.path.nfe=file:/example/nfe/${organizationId}
xst.fileresource.path.it=file:/example/invoice/it/${organizationId}

# The generic sftp credentials are for on-prem deployments. Assume one sftp server for
# locate, relate and nfe sftp tasks
cloud.sftp.host=localhost
cloud.sftp.username=Pj4+MP3////CXsw8nCCJ1YBiM8eArEoz
cloud.sftp.password=Pj4+MP3////CXsw8nCCJ1YBiM8eArEoz
cloud.sftp.locate.workingDir=locate
cloud.sftp.relate.workingDir=relate

cloud.http.locate.endpoint=https://HOST:PORT/Locate/faws/FileService/OROB-IMPORTS
cloud.http.locate.timeout.connect=30
cloud.http.locate.timeout.read=30
cloud.http.locate.compress=true
cloud.http.locate.oauth2=false
cloud.http.locate.username=Pj4+MAAAAADvHIxh8KlKpMb58080fuVH
cloud.http.locate.password=Pj4+MAAAAACxzvu3yc0wTglnR9h+w5f6



#####-------------------------------------------------------------------
##### cluster processes enabled
##### 
##### This configuration is a "master switch" that can enable/disable
##### ALL clustering-related processes, including replication, broadcasting,
##### and the SFTP file-transfer processes (loading promotions from Customer
##### Engagement, order broker updates, etc).  When disabled, this Xcenter
##### node really ends up just running the various DTX query servlets used
##### by Xstore.
cluster.processes.enabled=true

#####-------------------------------------------------------------------
##### cluster server number
##### 
##### THIS SETTING IS REQUIRED EVEN IF NOT RUNNING CLUSTERED INSTANCES. 
##### 
##### Each server instance must be configured with a UNIQUE server
##### number.
#####
##### In Xcenter, cluster.server-number is used by Xcenter's clustering
##### framework to uniquely identify each cluster node.
#####
##### Also noteworthy for Xcenter: this configuration is not given a
##### default value; if left unconfigured, Xcenter will fail to
##### start up until a server number is provided.
##### 
##### This number must be an integer from 1..{max int}.
#####-------------------------------------------------------------------
cluster.server-number=


#####-------------------------------------------------------------------
##### Replication publishing to Xcenter
#####-------------------------------------------------------------------
replication.publisher.resequencing_delay.seconds=10
replication.publisher.polling_interval.milliseconds=3000
replication.publisher.polling_maxbatchsize=400
replication.publisher.threads_per_orgid=3


## MS SQL Server EXAMPLES ##

# DB DRIVER
#dtv.datasource.connectionfactory=com.microsoft.sqlserver.jdbc.SQLServerDataSource

# DB URL
#dtv.local.db.url=jdbc:sqlserver://localhost;databaseName=xcenter_test
#dtv.xadmin.db.url=jdbc:sqlserver://localhost;databaseName=xadmin_test
#dtv.xcrepl.db.url=jdbc:sqlserver://localhost;databaseName=xcenter_replication

# DB URL (Unicode)
#dtv.local.db.url=jdbc:sqlserver://localhost;databaseName=xcenter_test;sendStringParametersAsUnicode=true
#dtv.xadmin.db.url=jdbc:sqlserver://localhost;databaseName=xadmin_test;sendStringParametersAsUnicode=true
#dtv.xcrepl.db.url=jdbc:sqlserver://localhost;databaseName=xcenter_replication;sendStringParametersAsUnicode=true

## JNDI EXAMPLES ##

# DB DRIVER
# Required for detection of SQL Dialect.  Configured as per prior examples.

# DB URL
# Note: These JNDI datasources must be configured on your application server prior to use.
# The format of the url is jndi:<jndi_path> (ie. Xcenter path jndi:jdbc/Local should be used
# with a database defined at jdbc/Local).
#dtv.local.db.url=jndi:jdbc/Local
#dtv.xadmin.db.url=jndi:jdbc/XcenterAdmin
#dtv.xcrepl.db.url=jndi:jdbc/XcenterReplication



deployment.FileType.JRE=zip
deployment.FileType.DATA=mnt,rep,reo,dat,xload
deployment.FileType.CONFIG=
deployment.FileType.APPUPD=jar,sig
deployment.FileType.COMPRESSED_DATA=
deployment.FileType.CIP=cip
deployment.FileType.NEW=newExt
deployment.FileType.ENVUPD=tar.gz

deployment.dataloader_file.character_encoding=UTF-8

# The valid file types for uploading the item message files.
fileUpload.FileType.HTML=htm,html
fileUpload.FileType.IMAGE=png,jpg,gif

# IDCS
#### Populated by CHEF ###
idp.connectionURL=https://identityproviderhost:port

#####-------------------------------------------------------------------
##### Auto dropped files are processed in two phases.
#####
##### 1. Data files are imported into Xcenter database through Xadmin's
##### integrated dataloader.
##### 2. Deployments of data files are staged for stores to download immediately 
##### or during store close to import into store database.
##### 
##### Phase 2 will not start till phase 1 is completed. In the case a client drops 
##### large number of data files, there will be a delay in the start of phase 2, 
##### which may be undesirable for the client.
##### 
##### To work around this performance issue, this property is introduced to turn 
##### off Xcenter data loading in phase 1 when set to true. If this property is 
##### missing or set to its default value of false, Xcenter data loading will be 
##### executed as usual. 
##### 
##### Please be aware that by flipping it to true disables Xcenter data loading.  
##### As a result, data files are not imported into Xcenter database. To ensure 
##### Xcenter data integrity, the client must instead execute standalone dataloader 
##### to import pertinent data files into Xcenter database.
#####-------------------------------------------------------------------
autoDrop.doNotLoadAutoDroppedFilesIntoXcenter=false

# Omnichannel Cloud Data Service
#####-------------------------------------------------------------------
#####  By default, it is false.
#####-------------------------------------------------------------------
ocds.onDemand.ui.enabled=false
#####-------------------------------------------------------------------
##### ocds.orgChainIds is a comma separated Xstore organization and OCDS 
##### chain mappings. For example, the following maps organization 1000 
##### to chain 1, and organization 2000 to chain 2. 
#####
##### ocds.orgChainIds=1000:1,2000:2
#####-------------------------------------------------------------------
ocds.orgChainIds=1000:1
ocds.connectionURL=https://localhost:443
ocds.connection.servicePath.prefix=/ords/ocds/omnichannel
ocds.connection.username=Pj4+MAAAAACRJ5aYAfLDEViGEAsnCi+v
ocds.connection.password=Pj4+MAAAAADP4xvfp0HjrR30FZOHlyss
#This is the number of days to retain OCDS Job History data in the database. 
#Setting to -1 will keep the data indefinitely.
ocds.retainJobHistory=90
#This is the minimum amount of time data must age in OCDS before it can be visible to Xcenter. 
#The offset helps to prevent related-data from becoming orphaned due to system latency. 
#The value should be greater than or equal to 30 seconds.
ocds.offset=30
#This specifies the number of records to request in calls to OCDS. 
#If no limit is defined then OCDS will determine the maximum number of records.
ocds.request.limit=-1
#This specifies if Retail Locations created from OCDS data are to use Till Accountability or not.
ocds.retailLocation.tillAccountability=false
#This specifies the Locale to use in Retail Locations created from OCDS data 
#when a LANG_ISO_CODE is not defined for a location.
ocds.retailLocation.locale=en_US
#This specifies the Tax Group Id assigned to non-taxable Items created from OCDS data.
ocds.taxGroupIdForNonTaxable=0
#This specifies if future date should be included to determine VAT code with the greatest active date.
ocds.includeFutureDate=false
#This specifies how the system will round when calculating tax. 
#Valid values are CEILING, DOWN, FLOOR, HALF_DOWN, HALF_EVEN, HALF_UP, and UP.
ocds.vatRoundingCode=HALF_UP
#This specifies how many decimal places to round to when calculating tax.
#The minimum rounding digit is 0 and the maximum rounding digit is 10.
ocds.vatRoundingDigits=2
#This specifies the ability to round at transaction level when calculating tax. 
#When setting is set to true, the calculated tax will be rounded at the transaction level. 
#When setting is set to false, the calculated tax is rounded at the line item level.
ocds.vatRoundingAtTransLevel=true

## For Xadmin cloud deployments only, file system location to save the integration task related public keys.
#integration.cloud.publickeys.path=

dtv.dataloader.enableRunSql=true

#XSS-606 Connection pool settings
dtv.local.db.poolmin=5
dtv.local.db.poolmax=150

dtv.xadmin.db.poolmin=2
dtv.xadmin.db.poolmax=20

dtv.xcrepl.db.poolmin=5
dtv.xcrepl.db.poolmax=50

#XSA23-88 ConnectionWaitTimeout
dtv.db.ConnectionWaitTimeout=60