# At the time of update/upgradde, If you dont want to update value of properties in  xstore_<country_id>.properties file , then update below configuration properties.. 
# If 'lev.copy.properties.value.from.backup' property is set to true then only xstore will look into xstore backup for each comma property passed against 'lev.list.properties.copy.from.backup' key,
# Possible values of 'lev.list.properties.copy.from.backup' property are any property key which is present in xstore_<countryId>.properties. 

lev.copy.properties.value.from.backup = true
lev.list.properties.copy.from.backup= hardware.cashdrawer,hardware.printer
lev.loyalty=lev.loyalty.enabled
