#encoding=UTF-8

# for IBM 1.9/1.12 on Linux:
#[XSA-633][Global]Patch versioning and name format - For patch 9 additional entries added in classpath hence accordingly changing value i.e  from classpath.23 to classpath.32 etc - Start
wrapper.java.classpath.32=/opt/javax-usb/etc
wrapper.java.classpath.33=/opt/ibm/javapos/etc
wrapper.java.classpath.34=/opt/ibm/javapos/lib/*.jar
wrapper.java.classpath.35=/opt/javax-usb/lib/*.jar
wrapper.java.library.path.2=/opt/ibm/javapos/lib
wrapper.java.library.path.3=/lib
#[XSA-633][Global]Patch versioning and name format - For patch 9 additional entries added in classpath hence accordingly changing value i.e  from classpath.23 to classpath.32 etc - End
