#encoding=UTF-8

wrapper.java.command=c:/jre/bin/java

# Load libraries for IBM hardware
wrapper.java.library.path.2=c:/windows/system32

# Load libraries from System32
wrapper.java.library.path.3=C:/POS/JavaPOS/lib
wrapper.java.library.path.4=C:/POS/JavaPOS/rxtx

# For NCR devices on Windows
#wrapper.java.library.path.4=C:/Program Files/NCR/Retail

#[XSA-633][Global]Patch versioning and name format - For patch 9 additional entries added in classpath hence accordingly changing value i.e  from classpath.23 to classpath.32 etc - Start
# for IBM 1.9/1.12 on Windows:
#wrapper.java.classpath.32=C:/POS/JavaPos/lib/*.jar
#wrapper.java.classpath.33=C:/POS/JavaPOS/rxtx/*.jar
wrapper.java.classpath.34=C:/POS/JavaPOS/Config

# For NCR devices on Windows
#wrapper.java.classpath.34=C:/Program Files/NCR/NCR JavaPOS/NCR*.jar
#wrapper.java.classpath.35=C:/Program Files/NCR/Retail/NCRRetailCommon.jar

wrapper.java.classpath.32=C:/Program Files/EPSON/UPOSDriverForFiscal/JavaPOS/*.jar
wrapper.java.classpath.33=C:/Program Files/EPSON/UPOSDriverForFiscal/JavaPOS
#[XSA-633][Global]Patch versioning and name format - For patch 9 additional entries added in classpath hence accordingly changing value i.e  from classpath.23 to classpath.32 etc - End

