DELETE FROM tnd_tndr WHERE organization_id = 1
    AND tndr_id IN ('ISSUE_STORE_CREDIT', 'STORE_CREDIT');


INSERT INTO tnd_tndr (organization_id, tndr_id, tndr_typcode, currency_id, description, display_order, create_date, create_user_id, update_date, update_user_id, flash_sales_display_order) VALUES (1,'ISSUE_STORE_CREDIT','VOUCHER','*','+ISSUE_STORE_CREDIT', NULL, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA', 80);
INSERT INTO tnd_tndr (organization_id, tndr_id, tndr_typcode, currency_id, description, display_order, create_date, create_user_id, update_date, update_user_id, flash_sales_display_order) VALUES (1,'STORE_CREDIT','VOUCHER','*','+STORE_CREDIT', NULL, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA', 330);

DELETE FROM com_translations WHERE organization_id = 1 AND translation_key='+ISSUE_STORE_CREDIT';
DELETE FROM com_translations WHERE organization_id = 1 AND translation_key='+STORE_CREDIT';
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUES (1, '+ISSUE_STORE_CREDIT', 'DEFAULT', '*', '*', 'Issue Store Credit', GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO com_translations (organization_id, translation_key, locale, org_code, org_value, translation, create_date, create_user_id, update_date, update_user_id) VALUES (1, '+STORE_CREDIT', 'DEFAULT', '*', '*', 'Store Credit', GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');

  -- *******************************************
  -- Tender Options
  -- *******************************************
  DELETE FROM tnd_tndr_options WHERE organization_id = 1
    AND config_element = '*'
    AND tndr_id IN ('ISSUE_STORE_CREDIT', 'STORE_CREDIT');
  
 INSERT INTO tnd_tndr_options (organization_id, tndr_id, auth_mthd_code, serial_id_nbr_req_flag, auth_req_flag, auth_expr_date_req_flag, pin_req_flag, cust_sig_req_flag, endorsement_req_flag, open_cash_drawer_req_flag, unit_count_req_code, mag_swipe_reader_req_flag, dflt_to_amt_due_flag, min_denomination_amt, reporting_group, effective_date, expr_date, min_days_for_return, max_days_for_return, cust_id_req_code, cust_association_flag, populate_system_count_flag, include_in_type_count_flag, suggested_deposit_threshold, suggest_deposit_flag, change_tndr_id, cash_change_limit, change_allowed_when_foreign, over_tender_overridable_flag, non_voidable_flag, disallow_split_tndr_flag, close_count_disc_threshold, cid_msr_req_flag, cid_keyed_req_flag, postal_code_req_flag, post_void_open_drawer_flag, assign_cash_drawer_req_flag, post_void_assign_drawer_flag, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT', NULL, 1, 0, 0, 0, 0, 0, 0,'TOTAL_NORMAL', 0, 1, NULL,'TENDER SUMMARY', NULL, NULL, 0, 999999, NULL, 0, 0, 0, 1000.000000, 0,'ISSUE_STORE_CREDIT', 5.000000, 0, 1, 0, 0, NULL, 0, 0, 0, 0, 0, 0, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_options (organization_id, tndr_id, auth_mthd_code, serial_id_nbr_req_flag, auth_req_flag, auth_expr_date_req_flag, pin_req_flag, cust_sig_req_flag, endorsement_req_flag, open_cash_drawer_req_flag, unit_count_req_code, mag_swipe_reader_req_flag, dflt_to_amt_due_flag, min_denomination_amt, reporting_group, effective_date, expr_date, min_days_for_return, max_days_for_return, cust_id_req_code, cust_association_flag, populate_system_count_flag, include_in_type_count_flag, suggested_deposit_threshold, suggest_deposit_flag, change_tndr_id, cash_change_limit, change_allowed_when_foreign, over_tender_overridable_flag, non_voidable_flag, disallow_split_tndr_flag, close_count_disc_threshold, cid_msr_req_flag, cid_keyed_req_flag, postal_code_req_flag, post_void_open_drawer_flag, assign_cash_drawer_req_flag, post_void_assign_drawer_flag, create_date, create_user_id, update_date, update_user_id) VALUES (1,'STORE_CREDIT', NULL, 1, 0, 0, 0, 0, 1, 0,'TOTAL_NORMAL', 0, 1, NULL,'TENDER SUMMARY', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 1000.000000, 0,'ISSUE_STORE_CREDIT', 5.000000, 0, 1, 0, 0, NULL, 0, 0, 0, 0, 0, 0, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
DELETE FROM tnd_tndr_availability WHERE organization_id = 1
    AND availability_code = 'CASH_DRAWER_REPORT'
    AND tndr_id IN ('ISSUE_STORE_CREDIT', 'STORE_CREDIT');
  
INSERT INTO tnd_tndr_availability (organization_id, tndr_id, availability_code, create_date, create_user_id, update_date, update_user_id) VALUES (1, 'ISSUE_STORE_CREDIT' , 'CASH_DRAWER_REPORT', GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_availability (organization_id, tndr_id, availability_code, create_date, create_user_id, update_date, update_user_id) VALUES (1, 'STORE_CREDIT' , 'CASH_DRAWER_REPORT', GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
 -- *******************************************
  -- Change availability
  -- *******************************************
  DELETE FROM tnd_tndr_availability WHERE organization_id = 1
    AND availability_code = 'CHANGE'
    AND tndr_id IN ('ISSUE_STORE_CREDIT');
INSERT INTO tnd_tndr_availability (organization_id, tndr_id, availability_code, create_date, create_user_id, update_date, update_user_id) VALUES (1, 'ISSUE_STORE_CREDIT', 'CHANGE', GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
 -- *******************************************
 -- Return with gift receipt availability
 -- *******************************************
 DELETE FROM tnd_tndr_availability WHERE organization_id = 1
   AND availability_code = 'RETURN_WITH_GIFT_RECEIPT'
   AND tndr_id IN ('ISSUE_STORE_CREDIT', 'STORE_CREDIT');
 
 INSERT INTO tnd_tndr_availability (organization_id, tndr_id, availability_code, create_date, create_user_id, update_date, update_user_id) VALUES (1, 'ISSUE_STORE_CREDIT', 'RETURN_WITH_GIFT_RECEIPT', GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');

-- *******************************************
-- Return with receipt availability
-- *******************************************
DELETE FROM tnd_tndr_availability WHERE organization_id = 1
  AND availability_code = 'RETURN_WITH_RECEIPT'
  AND tndr_id IN ('ISSUE_STORE_CREDIT', 'STORE_CREDIT');

INSERT INTO tnd_tndr_availability (organization_id, tndr_id, availability_code, create_date, create_user_id, update_date, update_user_id) VALUES (1, 'STORE_CREDIT', 'RETURN_WITH_RECEIPT', GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_availability (organization_id, tndr_id, availability_code, create_date, create_user_id, update_date, update_user_id) VALUES (1, 'ISSUE_STORE_CREDIT', 'RETURN_WITH_RECEIPT', GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
-- *******************************************
-- Return without receipt availability
-- *******************************************
DELETE FROM tnd_tndr_availability WHERE organization_id = 1
  AND availability_code = 'RETURN_WITHOUT_RECEIPT'
  AND tndr_id IN ('ISSUE_STORE_CREDIT', 'STORE_CREDIT');

INSERT INTO tnd_tndr_availability (organization_id, tndr_id, availability_code, create_date, create_user_id, update_date, update_user_id) VALUES (1, 'STORE_CREDIT', 'RETURN_WITHOUT_RECEIPT', GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_availability (organization_id, tndr_id, availability_code, create_date, create_user_id, update_date, update_user_id) VALUES (1, 'ISSUE_STORE_CREDIT', 'RETURN_WITHOUT_RECEIPT', GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
-- *******************************************
-- Sale
-- *******************************************
DELETE FROM tnd_tndr_availability WHERE organization_id = 1
  AND availability_code = 'SALE'
  AND tndr_id IN ('ISSUE_STORE_CREDIT','STORE_CREDIT');

INSERT INTO tnd_tndr_availability (organization_id, tndr_id, availability_code, create_date, create_user_id, update_date, update_user_id) VALUES (1, 'STORE_CREDIT', 'SALE', GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');

-- *******************************************
-- Tender Type code
-- *******************************************
DELETE FROM tnd_tndr_typcode WHERE organization_id = 1 and tndr_typcode='VOUCHER';

INSERT INTO tnd_tndr_typcode (organization_id, tndr_typcode, description, sort_order, unit_count_req_code, create_date, create_user_id, update_date, update_user_id) VALUES (1, 'VOUCHER', 'Voucher', 80, 'TOTAL_SHORT', GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');

DELETE FROM tnd_tndr_user_settings WHERE organization_id = 1
   AND tndr_id IN ('ISSUE_STORE_CREDIT', 'STORE_CREDIT');
 
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','CASHIER','CHANGE','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','CASHIER','DEFAULT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','CASHIER','RETURN_WITHOUTRECEIPT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','CASHIER','RETURN_WITHRECEIPT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','MANAGER','CHANGE','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','MANAGER','DEFAULT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','MANAGER','RETURN_WITHOUTRECEIPT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','MANAGER','RETURN_WITHRECEIPT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'STORE_CREDIT','CASHIER','DEFAULT','DEFAULT', 1.000000, NULL, 50.000000, NULL, NULL, 0.010000, 800.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'STORE_CREDIT','CASHIER','SALE','DEFAULT', 1.000000, NULL, 50.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'STORE_CREDIT','MANAGER','DEFAULT','DEFAULT', 1.000000, NULL, 100.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'STORE_CREDIT','MANAGER','SALE','DEFAULT', 1.000000, NULL, 100.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');

INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','LEADCASHIER','CHANGE','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','LEADCASHIER','DEFAULT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','LEADCASHIER','RETURN_WITHOUTRECEIPT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','LEADCASHIER','RETURN_WITHRECEIPT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','STOREMANAGER','CHANGE','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','STOREMANAGER','DEFAULT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','STOREMANAGER','RETURN_WITHOUTRECEIPT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','STOREMANAGER','RETURN_WITHRECEIPT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'STORE_CREDIT','LEADCASHIER','DEFAULT','DEFAULT', 1.000000, NULL, 50.000000, NULL, NULL, 0.010000, 800.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'STORE_CREDIT','LEADCASHIER','SALE','DEFAULT', 1.000000, NULL, 50.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'STORE_CREDIT','STOREMANAGER','DEFAULT','DEFAULT', 1.000000, NULL, 100.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'STORE_CREDIT','STOREMANAGER','SALE','DEFAULT', 1.000000, NULL, 100.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');

INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','COORPORATEUSER','CHANGE','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','COORPORATEUSER','DEFAULT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','COORPORATEUSER','RETURN_WITHOUTRECEIPT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','COORPORATEUSER','RETURN_WITHRECEIPT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','ADMIN','CHANGE','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','ADMIN','DEFAULT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','ADMIN','RETURN_WITHOUTRECEIPT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'ISSUE_STORE_CREDIT','ADMIN','RETURN_WITHRECEIPT','DEFAULT', 1.000000, NULL, 0.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'STORE_CREDIT','COORPORATEUSER','DEFAULT','DEFAULT', 1.000000, NULL, 50.000000, NULL, NULL, 0.010000, 800.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'STORE_CREDIT','COORPORATEUSER','SALE','DEFAULT', 1.000000, NULL, 50.000000, NULL, NULL, 0.010000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'STORE_CREDIT','ADMIN','DEFAULT','DEFAULT', 1.000000, NULL, 100.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');
INSERT INTO tnd_tndr_user_settings (organization_id, tndr_id, group_id, usage_code, entry_mthd_code, online_floor_approval_amt, online_ceiling_approval_amt, over_tndr_limit, offline_floor_approval_amt, offline_ceiling_approval_amt, min_accept_amt, max_accept_amt, max_refund_with_receipt, max_refund_wo_receipt, create_date, create_user_id, update_date, update_user_id) VALUES (1,'STORE_CREDIT','ADMIN','SALE','DEFAULT', 1.000000, NULL, 100.000000, NULL, NULL, 1.000000, 5000.000000, 1000.000000, 1000.000000, GETUTCDATE(), 'BASEDATA', GETUTCDATE(), 'BASEDATA');

commit;