################################################################################
## the contents of this file are loaded into java.lang.System.getProperties   ##
################################################################################

#!include root/system.properties

#dtv.pos.ui.overrideScreenSize.enabled=true
#dtv.pos.ui.overrideScreenSize.width=240
#dtv.pos.ui.overrideScreenSize.height=320

#********************************
# -- Localizeaczd Settings
#********************************

#--------------------------------------------------------------------------------------------
# Miscellaneous
#--------------------------------------------------------------------------------------------
dtv.pos.appmanagement.preflight.check.SequencePreFlightCheck.forceRepair=true
#dtv.util.security.AccessWarnings.disable=true

# Disable checking SSL certificates for the default Xstore's keystore and truststore.
ssl.certificate.check.enabled=false

java.util.logging.manager=org.apache.logging.log4j.jul.LogManager

# Determines if the synchronization process that updates retail location information, such as store information,
# tax mapping information, org hierarchy information, workstation information, till information, till float
# information, inventory bucket information, and inventory location bucket information, is performed on the
# primary register only, or performed on all registers as startup. If this properties does not exist, it
# defaults to TRUE and only runs on the primary register
dtv.register.startup.synchronize.primaryOnly=true
# #############################################################################
# # DataSourceConfig.xml configurations
# #############################################################################
dtv.datasource.db.ping.impl=dtv.data2.access.impl.OracleTnsPing

# Customer Display FrameLocationX,FrameLocationY,FrameWidth,FrameHeight
# dtv.pos.customerFramePosition=0,0,400,400

# Directory path for mock service response messages
dtv.xunit.service.AbstractTestServicePort.messageDir=res/test

# comma separted list of dtx hierarchy
dtv.data2.OverrideTypes=Customer,Country

# use process IO for djnative communication instead of sockets
nativeswing.interface.outProcess.communication=processio

#Mime encoding for mail attachments file name
mail.mime.encodefilename=true

dtv.locate.order.downloadInterval=15
dtv.locate.order.statusRequestInterval=30
dtv.register.openClose.useSystemDate=false

inventory.location.DefaultInventoryLocationId=DEFAULT
inventory.location.OnHandInventoryBucketId=ON_HAND
#Commented as in v21 value take from xstore.prop and we already write target
#which pich value from xstore_country specific prop and move to xstore.prop
#lev.sourceTXTArch.folder = C:\\Thirdpartycount\\Count\\archive\\
#lev.sourceTXT.folder = C:\\Thirdpartycount\\Count\\mainfile
#lev.levcount.filename = levcount
#lev.levcount.section.start = 25
#lev.levcount.section.end = 30
#lev.levcount.sku.start = 30
#lev.levcount.sku.end = 56
#lev.levcount.qty.start = 56
#lev.levcount.qty.end = 61
#lev.levcount.sleepinterval = 5000
#lev.levcount.file.minlinelength = 61
#lev.rejectFolder.folder = C:\\Thirdpartycount\\Count\\reject\\
#lev.file.extnsn = .txt
#dtv.data2.access.impl.PersistenceConstants.manageCase = true
dtv.pricing2.PriceProvider = lev.pos.pricing.LevLocationHierarchyPriceProvider
#lev.aos.envType = PROD
dtv.docbuilding.DocBuilderFieldFactory = lev.pos.docbuilding.LevPosDocBuilderFieldFactory

#oracle.retail.xstore.taxfree.globalblue.host = https://ic2integra.globalblue.com/service
#oracle.retail.xstore.taxfree.globalblue.ws.host = https://ic2integra.globalblue.com/bridge
#oracle.retail.xstore.taxfree.globalblue.ui = https://ic2integra.globalblue.com/ui/integra
#oracle.retail.xstore.taxfree.credential.extra = _GB_GB_PDF
tseStartDate = 2021-02-15
# RUN_SQL action is disabled for DataLoader by default. It is highly recommended that
# the RUN_SQL action only temporarily be enabled when there is necessity to use this action.
dtv.dataloader.enableRunSql=true
#Ecom Mule Endpoints. 
#lev.ecomorder.mule.testservice.url = https://mule.levi.com/omni-ecom-xstore-exp-api
#lev.ecomorder.mule.testservice.timeout = 30
#lev.ecomorder.mule.testservice.username = 0oa10fh5q50tHON8N0h8
#lev.ecomorder.mule.testservice.password = ZiFfsxa2GLJdd0qDMrC_HZBQjuUTxlGzR_S3rBdk
#dtv.relate.EcomGiftCardPrefix=12259
#dtv.relate.EcomGiftCardSeries=01
#dtv.relate.EcomGiftCard.SecurityUserId=200
lev.giftvoucher.GiftVoucherCardPrefix=19913
#LSE Loyalty changes
#lev.lseLoyalty.testservice.url=https://staging05.dtc.levi.com/mule/nextgen/lsa-loyalty/v2/member/
#lev.lseLoyalty.testservice.timeout=30
#lev.lseLoyalty.prodservice.url=https://staging05.dtc.levi.com/mule/nextgen/lsa-loyalty/v2/member/
#lev.lseLoyalty.prodservice.timeout=30

#Changes for ticket XSV21-1309
dtv.pos.appmanagement.preflight.check.SequencePreFlightCheck.forceRepair.INVENTORY_MOVEMENT=true

#Dev Workspace properties

dtv.CustomerId=TET
dtv.CustomerId.salt=TESTCORP

#--------------------------------------------------------------------------------------------
# SYSTEM IDENTITY
#--------------------------------------------------------------------------------------------
dtv.location.organizationId=1
dtv.location.storeNumber=13390
dtv.location.terminalNumber=1
dtv.location.primaryTerminalNumber=2
dtv.location.CurrencyId=INR
dtv.location.device.formfactor=desktop
dtv.location.CountryId = IN

dtv.relate.Auth =Pj4+MGE9NAGcbY+LeUmosdIBNOV9/weE5aMdkBWLIbHbnglSVPcyBQ==
dtv.relate.AuthTokenName = Org-User

dtv.datasource.relate.Enabled=true
dtv.relate.Host=levi1-stage-rce-wts.oracleindustry.com
dtv.relate.Port=443

