#Thu, 01 Sep 2022 18:36:03 +0530
#!include system.properties


# #############################################################################
# # system.properties configurations
# #############################################################################

dtv.CustomerId=TET
dtv.CustomerId.salt=TESTCORP

#--------------------------------------------------------------------------------------------
# SYSTEM IDENTITY
#--------------------------------------------------------------------------------------------
dtv.location.organizationId=1
dtv.location.storeNumber=101
dtv.location.terminalNumber=1
dtv.location.primaryTerminalNumber=1
dtv.location.device.formfactor=desktop
dtv.location.CountryId=US
dtv.location.CurrencyId=USD
dtv.location.RegionId=



# #############################################################################
# # Relate Integration
# #############################################################################
