#!include xstore.properties

dtv.location.terminalNumber=1
xstore.location.mobile.workstationId.range.start=101
xstore.location.mobile.workstationId.range.end=130

# Xstore mobile server alias
mobile.server.display.name=

#verifone decryption
xstorem.config.rsaPrivateKeyFilePath=
xstorem.config.rsaPrivateKeyPassword=



